language: c
sudo: true
dist: xenial

env:
  global:
    - NAME: obvius
    - ASDF_SYSTEM: obvius

matrix:
  include:
  - os: linux
    env:
      - TARGET_ARCH=i686
      - CFLAGS=-m32
      - EXTENSION=so
      - OUTPUT_FILE=lib$NAME.$EXTENSION.
  - os: linux
    env:
      - TARGET_ARCH=x86_64
      - CFLAGS=-m64
      - EXTENSION=so
      - OUTPUT_FILE=lib$NAME.$EXTENSION.
  - os: osx
    env:
      - TARGET_ARCH=i686
      - CFLAGS=-m32
      - EXTENSION=dylib
      - OUTPUT_FILE=lib$NAME.$EXTENSION
  - os: osx
    env:
      - TARGET_ARCH=x86_64
      - CFLAGS=-m64
      - EXTENSION=dylib
      - OUTPUT_FILE=lib$NAME.$EXTENSION

branches:
  only:
  - "/^v\\d+(\\.\\d+)+$/"


before_install:
  - >
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update -q
      sudo -E apt-get -yq --no-install-suggests --no-install-recommends install patchelf gcc-multilib xorg-dev
    fi
