language: c
sudo: true
dist: xenial

env:
  global:
    - NAME: obvius
    - ASDF_SYSTEM: obvius

matrix:
  include:
  - os: linux
    env:
      - TARGET_ARCH=i686
      - CFLAGS=-m32
      - EXTENSION=so
      - OUTPUT_FILE=lib$NAME.$EXTENSION.
  - os: linux
    env:
      - TARGET_ARCH=x86_64
      - CFLAGS=-m64
      - EXTENSION=so
      - OUTPUT_FILE=lib$NAME.$EXTENSION.
  - os: osx
    env:
      - TARGET_ARCH=i686
      - CFLAGS=-m32
      - EXTENSION=dylib
      - OUTPUT_FILE=lib$NAME.$EXTENSION
  - os: osx
    env:
      - TARGET_ARCH=x86_64
      - CFLAGS=-m64
      - EXTENSION=dylib
      - OUTPUT_FILE=lib$NAME.$EXTENSION

branches:
  only:
  - crosscompile 
#  - "/^v\\d+(\\.\\d+)+$/"


before_install:
  - >
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update -q
      sudo -E apt-get -yq --no-install-suggests --no-install-recommends install patchelf gcc-multilib xorg-dev
    fi


script:
  - export TARGET_FILE=$TRAVIS_BUILD_DIR/lib$NAME.$EXTENSION.-$TARGET_ARCH-$TRAVIS_OS_NAME-$TRAVIS_BRANCH
  - >
    cd $TRAVIS_BUILD_DIR/c-source/ && \
        mkdir build && \
	cd build && \
        cmake -G "Unix Makefiles" \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
        -DBUILD_SHARED_LIBS=ON \
        -DLIBRARY_OUTPUT_PATH=$TRAVIS_BUILD_DIR/c-source/lib \
        ..  && \
        cmake --build .

before_deploy:
  - mv $TRAVIS_BUILD_DIR/c-source/lib/$OUTPUT_FILE $TARGET_FILE
  - >
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      patchelf --set-rpath '@ORIGIN/' "$TARGET_FILE";
      patchelf --set-soname "lib$NAME.$EXTENSION" "$TARGET_FILE";
    fi
    
deploy:
  provider: releases
  api-key: $acceess_token
  file: [$TARGET_FILE]
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
